### ISSUE TITLE
[Bug] Gmail login (not imap) doesn't work, throws this error

### ISSUE THREAD

**Issue by ghost** [fstachura/email-bot#3]
Error

```
Traceback (most recent call last):
  File "/sec/root/email-bot/main.py", line 72, in <module>
    with MailboxClass(m["server"], port=m["port"]).login(m["login"], m["password"]) as mailbox:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/imap_tools/mailbox.py", line 300, in init
    super().init()
  File "/usr/local/lib/python3.11/dist-packages/imap_tools/mailbox.py", line 32, in init
    self.client = self._get_mailbox_client()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/imap_tools/mailbox.py", line 306, in _get_mailbox_client
    return imaplib.IMAP4_SSL(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imaplib.py", line 1323, in init
    IMAP4.init(self, host, port, timeout)
  File "/usr/lib/python3.11/imaplib.py", line 202, in init
    self.open(host, port, timeout)
  File "/usr/lib/python3.11/imaplib.py", line 1336, in open
    IMAP4.open(self, host, port, timeout)
  File "/usr/lib/python3.11/imaplib.py", line 312, in open
    self.sock = self._create_socket(timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imaplib.py", line 1326, in _create_socket
    sock = IMAP4._create_socket(self, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imaplib.py", line 302, in _create_socket
    return socket.create_connection(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known
```

**Comment by fstachura** [comment]
Can you please send the value of "mailbox.server" (from config.json)?

**Comment by ghost** [comment]
```
"server": "imap.google.com",
"port": 143,
```

**Comment by fstachura** [comment]
imap.google.com is not a real domain. You probably meant imap.gmail.com. The IMAP port for imap.gmail.com is 993. 

https://developers.google.com/gmail/imap/imap-smtp

**Comment by ghost** [comment]
Now, I get it. Though port 143 is default, google uses port 995

Thank you for your time. I'll try with this one and let you know the results.

**Comment by fstachura** [comment]
995 is used for POP3. This script only supports IMAP, which is usually exposed on 993

**Comment by ghost** [comment]
Getting same error.

I think Gmail login is faulty. Have to try with IMAP credentials

**Comment by ghost** [comment]
I couldn't run the 2nd command to activate env

Ran this with IMAP. Got this error.

![Screenshot_20240109-214817~2](https://github.com/fstachura/email-bot/assets/84121715/36ee0d45-89f4-4809-a53f-f047f3ea796d)

I don't know. Maybe broken package or file. imap_tools is not there.

I should install Linux and try.

Instead of using VPS.

**Comment by ghost** [comment]
Sorry for troubling you. I am totally new at this field.

I have been looking for this these past days. And I need this to work.

**Comment by fstachura** [comment]
This error means that the requirements were not properly installed. Running pip install without venv is unlikely to succeed in modern Linux distributions.

If you use debian or ubuntu, you could try installing the python3-imap-tools and python3-requests packages with apt.

**Comment by ghost** [comment]
I'm on Manjaro Linux

This time commands, everything went perfectly. Still got this error.
Tried both Gmail & Imap login

```
Traceback (most recent call last):
  File "/home/duck/Downloads/email-bot/main.py", line 72, in <module>
    with MailboxClass(m["server"], port=m["port"]).login(m["login"], m["password"]) as mailbox:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duck/Downloads/email-bot/.venv/lib/python3.11/site-packages/imap_tools/mailbox.py", line 300, in __init__
    super().__init__()
  File "/home/duck/Downloads/email-bot/.venv/lib/python3.11/site-packages/imap_tools/mailbox.py", line 32, in __init__
    self.client = self._get_mailbox_client()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/duck/Downloads/email-bot/.venv/lib/python3.11/site-packages/imap_tools/mailbox.py", line 306, in _get_mailbox_client
    return imaplib.IMAP4_SSL(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imaplib.py", line 1323, in __init__
    IMAP4.__init__(self, host, port, timeout)
  File "/usr/lib/python3.11/imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
  File "/usr/lib/python3.11/imaplib.py", line 1336, in open
    IMAP4.open(self, host, port, timeout)
  File "/usr/lib/python3.11/imaplib.py", line 312, in open
    self.sock = self._create_socket(timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imaplib.py", line 1326, in _create_socket
    sock = IMAP4._create_socket(self, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/imaplib.py", line 302, in _create_socket
    return socket.create_connection(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 827, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -2] Name or service not known```
```

#### Config.json
```
{
    "mailbox": {
        "server": "imap.google.com",
        "port": "993",
        "login": "example@gmail.com",
        "password": "",
        "starttls": false
    },
    "destinations": {
        "example2@gmail.com": "link"
    },
    "default_destination": "link"
}
```

**Comment by fstachura** [comment]
The server hostname is wrong.

> imap.google.com

You probably meant imap.gmail.com

**Comment by ghost** [comment]
Yay, it works! 🥳

**Another query**
If I want to increase the text characters, should I replace here?
2000 instead of 1000

  ```
  {msg.text[:1000]}
  ```

**Comment by backermanbd** [comment]
I think emails with 2000 chars or more don't get forwarded to the discord channel because of this:
```py
def idle(mailbox, callback):
    while True:
        logger.debug("idling")
        responses = mailbox.idle.wait(timeout=60*5)
        if responses:
            logger.debug("idle returned responses")
            callback() 
```
But I want these emails to be forwarded, too.

**Comment by ghost** [comment]
Gmail login doesn't work

```
Traceback (most recent call last):
  File "/home/anonxpro/Downloads/email-bot/main.py", line 72, in <module>
    with MailboxClass(m["server"], port=m["port"]).login(m["login"], m["password"]) as mailbox:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anonxpro/Downloads/email-bot/.venv/lib/python3.11/site-packages/imap_tools/mailbox.py", line 62, in login
    check_command_status(login_result, MailboxLoginError)
  File "/home/anonxpro/Downloads/email-bot/.venv/lib/python3.11/site-packages/imap_tools/utils.py", line 46, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxLoginError: Response status "OK" expected, but "NO" received. Data: [b'[ALERT] Application-specific password required: https://support.google.com/accounts/answer/185833 (Failure)']
```

**Comment by fstachura** [comment]
The error comes from GMail and it explains what you need to do to enable IMAP access to Google accounts 

> Application-specific password required: https://support.google.com/accounts/answer/185833

Please read the link from the error.

**Comment by ghost** [comment]
I have enabled it before but still didn't work. Tried again, doesn't work.

```
Traceback (most recent call last):
  File "/home/anonxpro/Downloads/email-bot/main.py", line 77, in <module>
    with MailboxClass(m["server"], port=m["port"]).login(m["login"], m["password"]) as mailbox:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/anonxpro/Downloads/email-bot/.venv/lib/python3.11/site-packages/imap_tools/mailbox.py", line 62, in login
    check_command_status(login_result, MailboxLoginError)
  File "/home/anonxpro/Downloads/email-bot/.venv/lib/python3.11/site-packages/imap_tools/utils.py", line 46, in check_command_status
    raise exception(command_result=command_result, expected=expected)
imap_tools.errors.MailboxLoginError: Response status "OK" expected, but "NO" received. Data: [b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)']
```

**Comment by backermanbd** [comment]
The Gmail app password is good for now. If you have free time, you can try fixing this.

**Comment by backermanbd** [comment]
Isn't it ironic?
This script uses a single IMAP account. The recipient address is also the same as the mail address. It can't be two.

And I can't filter email address of `From` field within the script.

**Comment by ghost** [comment]
> The error comes from GMail and it explains what you need to do to enable IMAP access to Google accounts

Is it working on your end?

**Comment by fstachura** [comment]
Yes, my gmail account with an app password seems to work ok with this script.

**Comment by ghost** [comment]
> Yes, my gmail account with an app password seems to work ok with this script.

My bad, then. I thought you were implementing a feature called "Gmail account without app password"
And I confirm your script works flawlessly.
